name = "DO"
uuid = "bdc82894-3457-4158-b3e7-4747090996eb"
authors = ["Flemming <holtorf@mit.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
